[tool.poetry]
name = "python-boilerplate"
version = "0.1.0"
description = "Project template"
authors = ["mwtmurphy <hi@mwtmurphy.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.10.12"
cookiecutter = "2.2.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
