name: Build test

on:
  push:
    branches:
      - main

jobs:
  test_cookiecutter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up python==3.10
      uses: actions/setup-python@v1
      with:
        python-version: '3.10'
        architecture: x64
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install poetry

    - name: Run makefile commands
      run: |
        make poetry_env
        make env
        make major
        make minor
        make patch
        make src_tests
        make src_tests_cov
