name: Build test

on:
  push:
    branches:
      - main

jobs:
  test_cookiecutter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        pip install cookiecutter

    - name: Create test repo
      run: |
        cookiecutter --no-input .

    - name: Run test repo shortcuts
      run: |
        cd project_name
        make poetry_env
        make env
        make major
        make minor
        make patch
        make src_tests
        make src_tests_cov
