name: Build test

on:
  push:
    branches:
      - main

jobs:
  test_cookiecutter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install cookiecutter
      run: |
        pip install cookiecutter poetry

    - name: Create template repo
      run: |
        cookiecutter --no-input .

    - name: Test repo shortcuts
      run: |
        cd project_name
        make poetry_env
        make env
        make major
        make minor
        make patch
        make src_tests
        make src_tests_cov
